# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='status',
            field=models.CharField(choices=[('d', 'done'), ('p', 'pending'), ('w', 'working')], default='done', max_length=1),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
